Repository biralavor/42_minishell, pull requests merged in 2024-10, with the labels that each got.

#375 improving str pointer security, without breaking tests
  src/01_lexer/07.token_list_functions.c
  src/05.loop_routine.c
  src/06_builtins/48.builtin_exit.c
Labels: enhancement

#373 adding is_heredoc_running and heredoc_fd_reset
  headers/parser.h
  src/01_lexer/07.token_list_functions.c
  src/02.signals.c
  src/02_parser/20.manage_heredoc.c
  src/05.loop_routine.c
  src/06_builtins/48.builtin_exit.c
Labels: enhancement

#354 339 fix redirects minishell tester 45 of 75
  Makefile
  headers/executor.h
  headers/lexer.h
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/11.state61_to_state90.c
  src/01_lexer/13.lexer_utils.c
  src/02_parser/17.check_redirects.c
  src/02_parser/18.check_redirects_utils.c
  src/02_parser/19.error_manager_parser.c
  src/02_parser/20.manage_heredoc.c
  src/03_binary_tree/21.building_tree.c
  src/04_tree_execution/23.tree_execution.c
  src/04_tree_execution/26.manage_pipe.c
  src/04_tree_execution/27.manage_redirects.c
  src/04_tree_execution/28.manage_subshell.c
  src/04_tree_execution/manage_redirects_utils.c
  src/05.loop_routine.c
  src/exit_utils.c
  src/minishell_main.c
Labels: bug

#377 adding extras tester and 146 items tester for actions
  .github/workflows/minishell_tester_146_items.yml
  .github/workflows/minishell_tester_extras.yml
Labels: enhancement

#370 building 2nd version of signals implementation
  headers/minishell.h
  headers/parser.h
  src/01.main.c
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/11.state61_to_state90.c
  src/02.signals.c
  src/02_parser/17.check_redirects.c
  src/02_parser/18.check_redirects_utils.c
  src/02_parser/20.manage_heredoc.c
  src/04_tree_execution/23.tree_execution.c
  src/04_tree_execution/27.manage_redirects.c
  src/05.loop_routine.c
  src/06_builtins/48.builtin_exit.c
Labels: enhancement

#383 fixing echo when -n is activated
  src/06_builtins/38.builtin_manager.c
  src/06_builtins/39.builtin_utils.c
  src/06_builtins/40.builtin_echo.c
Labels: bug

#387 386 feat valgrind actions for minishell tester redirects
  .github/workflows/minishell_tester_valgrind.yml
Labels: enhancement

#392 fixing history when command not found
  src/07_command_execution/50.command_runner.c
Labels: bug

#397 Feat heredoc expansions
  src/02_parser/20.manage_heredoc.c
  src/04.env_init_utils.c
  src/04_tree_execution/26.manage_pipe.c
  src/07_command_execution/50.command_runner.c
Labels: enhancement

#399 398 fix if command not found 2nd attempt
  headers/parser.h
  libs/libft/Makefile
  libs/libft/includes/libft.h
  libs/libft/src/ft_strcmp.c
  src/05.loop_routine.c
  src/06_builtins/37.builtin_detectors.c
  src/06_builtins/38.builtin_manager.c
Labels: bug

#401 fixing exit message
  src/06_builtins/48.builtin_exit.c
Labels: enhancement

#403 protecting it if array is NULL
  .github/workflows/minishell_tester_146_items.yml
  .github/workflows/minishell_tester_builtins.yml
  .github/workflows/minishell_tester_extras.yml
  .github/workflows/minishell_tester_heredoc.yml
  .github/workflows/minishell_tester_mandatory.yml
  .github/workflows/minishell_tester_pipes.yml
  .github/workflows/minishell_tester_redirects.yml
  .github/workflows/minishell_tester_syntax.yml
  .github/workflows/norminette.yml
  .github/workflows/our_own_tester.yml
  src/04.env_init_utils.c
Labels: bug

#406 new child process is running
  src/04_tree_execution/26.manage_pipe.c
  src/07_command_execution/50.command_runner.c
Labels: enhancement

#408 building new version of is_heredoc_running()
  src/02.signals.c
  src/02_parser/20.manage_heredoc.c
Labels: enhancement

#410 409 feat heredoc forcing exit warning
  headers/parser.h
  src/02_parser/20.manage_heredoc.c
Labels: enhancement

#412 adding a counter at norminette action
  .github/workflows/norminette.yml
Labels: enhancement

#416 invalid read solved at PIPES
  src/01_lexer/08.get_state.c
  src/01_lexer/11.state61_to_state90.c
  src/01_lexer/13.lexer_utils.c
Labels: leak

#430 Tree execution is up to date with Norminette.
  Makefile
  headers/executor.h
  src/04_tree_execution/26.manage_pipe.c
  src/04_tree_execution/29.manage_single_cmd.c
  src/04_tree_execution/manage_pipe_utils.c
Labels: enhancement

#428 Lexer is up to date with Norminette.
  src/01_lexer/07.token_list_functions.c
Labels: enhancement

#434 fix norminette in rest of expansions
  Makefile
  src/05_expansions/34.expansion_env_var.c
  src/05_expansions/35.expansion_env_var_utils.c
  src/05_expansions/expansion_env_var_utils_2.c
Labels: enhancement

#439 adding new files into our_own_tester
  _ci_cd/minishell_main_tester.c
Labels: bug

#437 removing exit_code watcher at valgrind actions
  .github/workflows/minishell_tester_valgrind.yml
Labels: enhancement

#440 updating exit_status at command_runner()
  headers/execution.h
  headers/minishell.h
  src/04_tree_execution/23.tree_execution.c
  src/04_tree_execution/25.manage_or_and.c
  src/04_tree_execution/29.manage_single_cmd.c
  src/07_command_execution/50.command_runner.c
Labels: enhancement

#441 best version of execve error manager
  headers/execution.h
  src/07_command_execution/50.command_runner.c
Labels: enhancement

#445 avoiding add spaces into history
  headers/minishell.h
  src/01.main.c
Labels: enhancement

#447 fixing exit for many arguments
  src/06_builtins/48.builtin_exit.c
Labels: bug

#453 Fix EXIT with arguments
  src/06_builtins/48.builtin_exit.c
Labels: bug

#448 avoiding Makefile relink
  Makefile
  libs/libft/Makefile
Labels: enhancement

#454 removing invalid free at tilde
  src/05_expansions/33.expansion_tilde.c
Labels: leak

#461 fix seg fault adding flag var in open_redir_function
  src/04_tree_execution/27.manage_redirects.c
Labels: bug

#462 443 remove leak at command with arg
  src/04.env_init_utils.c
  src/04_tree_execution/29.manage_single_cmd.c
Labels: bug, leak

#466 456 fix cd relative path with a lot of dot dot
  Makefile
  headers/builtins.h
  headers/expansion.h
  src/05_expansions/30.expansion_manager.c
  src/05_expansions/expansion_parent_dir.c
  src/06_builtins/41.builtin_cd.c
Labels: bug

#468 avoiding double prompt, after a SIGINT
  src/02.signals.c
Labels: bug

#470 removing sequencial quotes when necessary
  src/05_expansions/32.expansion_quotes.c
Labels: bug

#471 450 fix builtin export 3rd attempt
  src/03.env_init.c
  src/04.env_init_utils.c
  src/06_builtins/44.builtin_export.c
  src/06_builtins/45.builtin_export_utils.c
Labels: bug

#478 starting with slash already detected
  src/05_expansions/expansion_parent_dir.c
Labels: bug

#479 heredoc without null delimiter working
  src/02_parser/20.manage_heredoc.c
Labels: bug

#475 474 fix leak at command not found with args
  Makefile
  _ci_cd/minishell_main_tester.c
  headers/execution.h
  src/04.env_init_utils.c
  src/04_tree_execution/29.manage_single_cmd.c
  src/07_command_execution/50.command_runner.c
  src/07_command_execution/51.command_runner_utils.c
  src/07_command_execution/execve_error_manager.c
Labels: leak

#481 bug fixed - heredoc case when delimiter is
  libs/libft/src/ft_strncmp.c
  src/02_parser/20.manage_heredoc.c
  src/05_expansions/32.expansion_quotes.c
Labels: bug

#482 463 fix unset path
  headers/builtins.h
  src/05_expansions/31.expansion_detectors.c
  src/06_builtins/45.builtin_export_utils.c
  src/06_builtins/46.builtin_unset.c
Labels: bug

#483 fix when single quotes and multiple commands
  src/01_lexer/11.state61_to_state90.c
Labels: bug

#488 fix HEREDOC to get delimiter with ft_strcmp
  src/02_parser/20.manage_heredoc.c
Labels: bug

#494 493 fix export for value with quotes
  src/01_lexer/11.state61_to_state90.c
  src/05_expansions/30.expansion_manager.c
  src/06_builtins/45.builtin_export_utils.c
Labels: enhancement

#491 1st try removing dup
  Makefile
  src/04_tree_execution/29.manage_single_cmd.c
  src/07_command_execution/50.command_runner.c
  src/07_command_execution/51.command_runner_utils.c
  src/07_command_execution/execve_error_manager.c
Labels: leak

#492 486 fix export if user sends multiples vars
  headers/builtins.h
  src/01_lexer/11.state61_to_state90.c
  src/03.env_init.c
  src/05_expansions/30.expansion_manager.c
  src/06_builtins/38.builtin_manager.c
  src/06_builtins/44.builtin_export.c
  src/06_builtins/45.builtin_export_utils.c
Labels: bug, enhancement

#496 replacing strNcmp with strcmp
  src/05_expansions/34.expansion_env_var.c
  src/06_builtins/39.builtin_utils.c
Labels: enhancement

#498 fix if all_paths doesnt exist
  src/07_command_execution/51.command_runner_utils.c
Labels: bug

#500 fix in state_200
  src/02_parser/16.state200_to_state300.c
Labels: bug

#503 updating lexer headers
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/08.get_state.c
  src/01_lexer/09.state10_to_state30.c
  src/01_lexer/10.state40_to_state60.c
  src/01_lexer/11.state61_to_state90.c
  src/01_lexer/12.error_manager_lexer.c
  src/01_lexer/13.lexer_utils.c
Labels: documentation

#504 applying norminette at headers
  headers/builtins.h
  headers/environment.h
  headers/error_manager.h
  headers/parser.h
  src/02.signals.c
  src/03.env_init.c
  src/04.env_init_utils.c
  src/tty_proprieties.c
Labels: documentation

#510 fix leaks at unset
  headers/builtins.h
  src/03.env_init.c
  src/06_builtins/46.builtin_unset.c
Labels: bug

#515 fix adding quotes to builtins_with_possible_args_manager function
  src/06_builtins/38.builtin_manager.c
Labels: enhancement

#517 adding security check at state 90 and fixing check_single
  src/01_lexer/11.state61_to_state90.c
  src/01_lexer/13.lexer_utils.c
Labels: enhancement

#520 implemenation of OLDPWD
  headers/minishell.h
  src/06_builtins/41.builtin_cd.c
Labels: enhancement

#508 Fix Ctrl-C implementation
  Makefile
  headers/lexer.h
  headers/minishell.h
  headers/parser.h
  src/01.main.c
  src/01_lexer/07.token_list_functions.c
  src/02.signals.c
  src/02_parser/20.manage_heredoc.c
  src/02_parser/heredoc_expansions.c
  src/02_parser/heredoc_fds.c
  src/03_binary_tree/21.building_tree.c
  src/04_tree_execution/27.manage_redirects.c
  src/05.loop_routine.c
Labels: bug

#524 lexer - fix norminette
  Makefile
  headers/lexer.h
  src/01_lexer/11.state61_to_state90.c
  src/01_lexer/13.lexer_utils.c
  src/01_lexer/lexer_utils_2.c
Labels: documentation

#525 tree execution norminette update
  src/04_tree_execution/29.manage_single_cmd.c
Labels: documentation

#526 expansion - norminette update
  src/05_expansions/32.expansion_quotes.c
  src/05_expansions/expansion_parent_dir.c
Labels: documentation

#528 builtin - 1st part of norminette update
  headers/builtins.h
  src/06_builtins/38.builtin_manager.c
  src/06_builtins/40.builtin_echo.c
  src/06_builtins/41.builtin_cd.c
  src/06_builtins/44.builtin_export.c
  src/06_builtins/45.builtin_export_utils.c
  src/06_builtins/46.builtin_unset.c
  src/06_builtins/47.builtin_env.c
Labels: documentation

#532 fixing leak and invalid read when SIG is activated in HereDoc
  Makefile
  headers/parser.h
  src/02_parser/20.manage_heredoc.c
Labels: leak

#537 fix rl_displayLine after multiples ctrlC
  headers/minishell.h
  src/01.main.c
  src/02.signals.c
Labels: bug

#542 fix invalid read at convert_envs_to_array
  src/07_command_execution/51.command_runner_utils.c
Labels: bug

#546 empty quotes working
  src/04_tree_execution/29.manage_single_cmd.c
  src/06_builtins/37.builtin_detectors.c
Labels: bug

#549 including single quotes in tree_execution function
  src/04_tree_execution/23.tree_execution.c
Labels: bug

#555 fixing invalid read at flag - fix bonus test 01
  src/04_tree_execution/27.manage_redirects.c
Labels: bug

#551 adding exit status code on HereDoc when Success
  src/02_parser/20.manage_heredoc.c
Labels: enhancement

#557 applying norminette
  headers/builtins.h
  headers/lexer.h
Labels: documentation

#558 applying norminette
  Makefile
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/token_list_utils.c
  src/02_parser/16.state200_to_state300.c
  src/06_builtins/37.builtin_detectors.c
Labels: documentation

#553 fix sigfault when heredoc with cat and ctrl d
  Makefile
  _tdd_utils/ft_lst_printer.c
  _tdd_utils/ft_tree_printer.c
  headers/minishell.h
  headers/parser.h
  src/01.main.c
  src/01_lexer/07.token_list_functions.c
  src/02.minishell_init.c
  src/02_parser/20.manage_heredoc.c
  src/02_parser/heredoc_errors.c
  src/02_parser/heredoc_expansions.c
  src/02_parser/heredoc_fds.c
  src/05.loop_routine.c
Labels: bug, leak

#560 Builtins CD - norminette update
  src/06_builtins/41.builtin_cd.c
Labels: documentation

#562 fix heredoc
  src/02_parser/20.manage_heredoc.c
  src/02_parser/heredoc_expansions.c
Labels: bug

#567 apply norminette in all except parser
  src/02_parser/16.state200_to_state300.c
  src/07_command_execution/50.command_runner.c
Labels: documentation

#573 568 apply norminette at heredoc
  Makefile
  headers/parser.h
  src/02_parser/20.manage_heredoc.c
  src/02_parser/heredoc_expansions.c
  src/02_parser/manage_heredoc_eof.c
  src/05.loop_routine.c
  src/05_expansions/31.expansion_detectors.c
Labels: documentation

#564 Fix invalid read, cd segfault
  .nfs00000000104101300000309f
  libs/libft/src/ft_putstr_fd.c
  src/02.signals.c
  src/04_tree_execution/27.manage_redirects.c
  src/05_expansions/30.expansion_manager.c
  src/05_expansions/34.expansion_env_var.c
  src/05_expansions/expansion_parent_dir.c
  src/06_builtins/41.builtin_cd.c
Labels: bug

#572 fix error msg at unset
  src/06_builtins/46.builtin_unset.c
Labels: enhancement

#578 fix leak at check_question_mark_for_heredoc
  src/02_parser/heredoc_expansions.c
Labels: leak

#581 adding actions for carol_ogata_tester
  .github/workflows/carologata_tester.yml
Labels: enhancement
