Repository biralavor/42_minishell, pull requests merged in 2024-09, with the labels that each got.

#177 149 fix builtin cd treat error for chdir to file
  Makefile
  _ci_cd/test_files/minishell_main_tester.c
  headers/builtins.h
  headers/minishell.h
  src/builtins/25.builtins_cd.c
  src/builtins/builtins_cd_utils.c
Labels: bug

#179 177 fix builtin cd last parent dir
  headers/builtins.h
  src/builtins/25.builtins_cd.c
Labels: bug

#180 bugfix dealing with leaks through changing free(input) location
  Makefile
  src/01.simple_main.c
Labels: bug

#183 removing harcode
  src/builtins/23.builtins_manager.c
Labels: bug

#186 184 fix pipe implementation
  src/executor/32.execve.c
  src/executor/33.execve_utils.c
  src/executor/36.manage_pipe.c
Labels: bug

#189 removing double free
  _ci_cd/test_files/minishell_main_tester.c
  src/builtins/29.builtins_unset.c
Labels: bug

#190 187 fix pipe if command error
  src/executor/32.execve.c
  src/executor/36.manage_pipe.c
Labels: bug

#191 removing hardcode
  src/builtins/23.builtins_manager.c
Labels: bug

#193 fixing fd
  libs/libft/src/ft_putstr_fd.c
Labels: bug

#199 adding exit argument cases 1, 2, 3
  src/builtins/34.builtins_exit.c
Labels: enhancement

#203 applying exit status holder
  src/builtins/25.builtins_cd.c
  src/builtins/builtins_cd_utils.c
Labels: enhancement

#205 applying exit status holder
  src/builtins/26.builtins_pwd.c
  src/builtins/30.builtins_env.c
Labels: enhancement

#207 206 spliting builtin exit function too many lines
  headers/builtins.h
  src/builtins/34.builtins_exit.c
Labels: bug

#212 211 feat tree holder for t tree
  headers/executor.h
  src/02.check_userinput.c
  src/builtins/34.builtins_exit.c
  src/executor/19.building_tree.c
Labels: enhancement

#217 195 feat exit status holder at builtins
  Makefile
  _ci_cd/test_files/minishell_main_tester.c
  headers/builtins.h
  headers/executor.h
  headers/minishell.h
  src/01.simple_main.c
  src/02.check_userinput.c
  src/builtins/23.builtins_manager.c
  src/builtins/24.builtins_echo.c
  src/builtins/25.builtins_cd.c
  src/builtins/26.builtins_pwd.c
  src/builtins/30.builtins_env.c
  src/builtins/34.builtins_exit.c
  src/builtins/builtins_cd_utils.c
  src/builtins/builtins_exit_utils.c
  src/executor/19.building_tree.c
  src/executor/32.execve.c
  src/executor/36.manage_pipe.c
  src/expansions/expansion_env_variable.c
  src/expansions/expansion_question.c
Labels: enhancement

#218 feature - redirects at execution
  3-file.txt
  Makefile
  _ci_cd/test_files/minishell_main_tester.c
  headers/executor.h
  headers/minishell.h
  src/executor/19.building_tree.c
  src/executor/32.execve.c
  src/executor/manage_redirects.c
  src/parser/11.syntax_analysis.c
  src/parser/16.redir_manager.c
  src/parser/17.redir_utils.c
Labels: enhancement

#221 220 fix builtin export with args
  headers/builtins.h
  headers/environment.h
  src/01.simple_main.c
  src/builtins/27.builtins_export.c
  src/builtins/28.builtins_export_utils.c
  src/executor/21.env_init.c
  src/executor/22.env_init_utils.c
Labels: bug

#226 194 fix special cases from pipe
  _tdd_utils/ft_array_printer.c
  _tdd_utils/ft_lst_printer.c
  src/executor/32.execve.c
  src/executor/33.execve_utils.c
  src/executor/36.manage_pipe.c
Labels: bug

#227 removing quotes - inside expansion
  Makefile
  _ci_cd/test_files/minishell_main_tester.c
  headers/expansion.h
  src/expansions/expansion_detectors_middle.c
  src/expansions/expansion_manager.c
  src/expansions/expansion_quotes.c
Labels: enhancement

#229 228 moving tilde from builtin cd to expansion
  Makefile
  _ci_cd/test_files/minishell_main_tester.c
  headers/expansion.h
  src/builtins/25.builtins_cd.c
  src/expansions/expansion_home.c
  src/expansions/expansion_manager.c
Labels: bug, enhancement

#230 fixing env printer
  _tdd_utils/ft_env_printer.c
Labels: bug

#234 231 remove memory leak from command manager
  _tdd_utils/ft_array_printer.c
  libs/libft/Makefile
  libs/libft/includes/libft.h
  libs/libft/src/ft_merge_strings.c
  src/executor/32.execve.c
  src/executor/33.execve_utils.c
  src/expansions/expansion_home.c
Labels: bug

#238 236 fix expansion dollar sign more than one
  Makefile
  _ci_cd/test_files/minishell_main_tester.c
  _tdd_utils/ft_lst_printer.c
  headers/expansion.h
  src/executor/env_var_rules.c
  src/expansions/expansion_detectors.c
  src/expansions/expansion_detectors_start.c
  src/expansions/expansion_env_variable.c
  src/expansions/expansion_manager.c
  src/expansions/expansion_quotes.c
Labels: bug, enhancement

#245 216 tobe merged
  .vscode/launch.json
  headers/builtins.h
  headers/executor.h
  headers/parser.h
  src/01.simple_main.c
  src/02.check_userinput.c
  src/executor/19.building_tree.c
  src/executor/20.building_tree_utils.c
  src/executor/32.execve.c
  src/executor/35.manage_or_and.c
  src/executor/36.manage_pipe.c
  src/executor/manage_redirects.c
  src/executor/utils.c
  src/lexer/04.token_list_functions.c
  src/parser/11.syntax_analysis.c
  src/parser/15.state300.c
  src/parser/16.redir_manager.c
  src/parser/17.redir_utils.c
  src/parser/18.error_manager_parser.c
Labels: bug, enhancement

#250 249 reorganizing files part 02
  Makefile
  _ci_cd/test_files/minishell_main_tester.c
  _ci_cd/test_files/test11_syntax_redirects.c
  headers/executor.h
  headers/minishell.h
  headers/parser.h
  src/01.main.c
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/08.get_state.c
  src/01_lexer/09.state10_to_state30.c
  src/01_lexer/10.state40_to_state60.c
  src/01_lexer/11.state61_to_state90.c
  src/01_lexer/12.error_manager_lexer.c
  src/01_lexer/13.lexer_utils.c
  src/02.signals.c
  src/02_parser/14.syntax_analysis.c
  src/02_parser/15.state100.c
  src/02_parser/16.state200_to_state300.c
  src/02_parser/17.check_redirects.c
  src/02_parser/18.check_redirects_utils.c
  src/02_parser/19.error_manager_parser.c
  src/02_parser/20.manage_heredoc.c
  src/03.env_init.c
  src/03_binary_tree/21.building_tree.c
  src/03_binary_tree/22.building_tree_utils.c
  src/04.env_init_utils.c
  src/04_tree_execution/23.tree_execution.c
  src/04_tree_execution/24.tree_execution_utils.c
  src/04_tree_execution/25.manage_or_and.c
  src/04_tree_execution/26.manage_pipe.c
  src/04_tree_execution/27.manage_redirects.c
  src/04_tree_execution/28.manage_single_cmd.c
  src/05.loop_routine.c
  src/05_expansions/29.expansion_manager.c
  src/05_expansions/30.expansion_detectors.c
  src/05_expansions/31.expansion_quotes.c
  src/05_expansions/32.expansion_tilde.c
  src/05_expansions/33.expansion_env_var.c
  src/05_expansions/34.expansion_env_var_utils.c
  src/05_expansions/35.expansion_question.c
  src/06_builtins/36.builtin_detectors.c
  src/06_builtins/37.builtin_manager.c
  src/06_builtins/38.builtin_utils.c
  src/06_builtins/39.builtin_echo.c
  src/06_builtins/40.builtin_cd.c
  src/06_builtins/41.builtin_cd_utils.c
  src/06_builtins/42.builtin_pwd.c
  src/06_builtins/43.builtin_export.c
  src/06_builtins/44.builtin_export_utils.c
  src/06_builtins/45.builtin_unset.c
  src/06_builtins/46.builtin_env.c
  src/06_builtins/47.builtin_exit.c
  src/06_builtins/48.builtin_exit_utils.c
  src/07_command_execution/49.command_runner.c
  src/07_command_execution/50.command_runner_utils.c
Labels: documentation

#251 247 remove memory leak pipe with cat
  headers/executor.h
  src/01.main.c
  src/03.env_init.c
  src/04.env_init_utils.c
  src/04_tree_execution/26.manage_pipe.c
  src/07_command_execution/49.command_runner.c
Labels: leak

#255 252 fix command not found with double free
  .github/workflows/program_builder.yml
  Makefile
  _ci_cd/Makefile
  _ci_cd/minishell_main_tester.c
  _ci_cd/minunit_utils.c
  headers/executor.h
  src/03_binary_tree/21.building_tree.c
  src/03_binary_tree/22.building_tree_utils.c
  src/04_tree_execution/26.manage_pipe.c
  src/04_tree_execution/28.manage_single_cmd.c
  src/05_expansions/33.expansion_env_var.c
  src/06_builtins/43.builtin_export.c
  src/06_builtins/47.builtin_exit.c
  src/07_command_execution/49.command_runner.c
Labels: bug, leak

#257 fixing leak at tilde
  src/05_expansions/32.expansion_tilde.c
Labels: bug, leak

#260 applying env rules at arg handle runner
  src/06_builtins/43.builtin_export.c
  src/06_builtins/44.builtin_export_utils.c
Labels: enhancement

#261 222 fix builtin exportto not duplicate a new env if exists
  headers/builtins.h
  src/05_expansions/34.expansion_env_var_utils.c
  src/06_builtins/43.builtin_export.c
  src/06_builtins/44.builtin_export_utils.c
  src/06_builtins/46.builtin_env.c
Labels: bug, enhancement

#262 157 rebuild envs without leaks
  .vscode/settings.json
  headers/builtins.h
  headers/environment.h
  src/03.env_init.c
  src/04.env_init_utils.c
  src/05_expansions/34.expansion_env_var_utils.c
  src/06_builtins/43.builtin_export.c
  src/06_builtins/44.builtin_export_utils.c
  src/06_builtins/46.builtin_env.c
Labels: bug, leak

#264 building a new method to copy env_table for sorting it
  headers/builtins.h
  src/06_builtins/43.builtin_export.c
Labels: bug, leak

#267 fixing builtin lexeme len comparison
  src/06_builtins/36.builtin_detectors.c
Labels: bug

#269 disabling env printer
  src/06_builtins/43.builtin_export.c
Labels: enhancement

#272 fixing fork execution
  src/07_command_execution/49.command_runner.c
Labels: bug

#277 Ordered files and subshell
  Makefile
  _ci_cd/minishell_main_tester.c
  headers/executor.h
  manage_subshell.c
  src/03_binary_tree/21.building_tree.c
  src/04_tree_execution/23.tree_execution.c
  src/04_tree_execution/28.manage_subshell.c
  src/04_tree_execution/29.manage_single_cmd.c
  src/05_expansions/30.expansion_manager.c
  src/05_expansions/31.expansion_detectors.c
  src/05_expansions/32.expansion_quotes.c
  src/05_expansions/33.expansion_tilde.c
  src/05_expansions/34.expansion_env_var.c
  src/05_expansions/35.expansion_env_var_utils.c
  src/05_expansions/36.expansion_question.c
  src/06_builtins/37.builtin_detectors.c
  src/06_builtins/38.builtin_manager.c
  src/06_builtins/39.builtin_utils.c
  src/06_builtins/40.builtin_echo.c
  src/06_builtins/41.builtin_cd.c
  src/06_builtins/42.builtin_cd_utils.c
  src/06_builtins/43.builtin_pwd.c
  src/06_builtins/44.builtin_export.c
  src/06_builtins/45.builtin_export_utils.c
  src/06_builtins/46.builtin_unset.c
  src/06_builtins/47.builtin_env.c
  src/06_builtins/48.builtin_exit.c
  src/06_builtins/49.builtin_exit_utils.c
  src/07_command_execution/50.command_runner.c
  src/07_command_execution/51.command_runner_utils.c
Labels: enhancement

#280 updating fd at echo
  src/06_builtins/40.builtin_echo.c
Labels: enhancement

#284 fixing size
  src/06_builtins/38.builtin_manager.c
Labels: bug

#286 fixing expansion files
  headers/expansion.h
  src/05_expansions/30.expansion_manager.c
  src/05_expansions/31.expansion_detectors.c
  src/05_expansions/32.expansion_quotes.c
  src/05_expansions/34.expansion_env_var.c
  src/05_expansions/36.expansion_question.c
Labels: bug

#291 290 fix builtin exit when user send weird args
  src/05.loop_routine.c
  src/06_builtins/48.builtin_exit.c
  src/06_builtins/49.builtin_exit_utils.c
Labels: bug, enhancement

#294 improving arg security for export
  src/06_builtins/45.builtin_export_utils.c
Labels: bug

#295 292 fix unset double free detected
  headers/builtins.h
  src/01_lexer/07.token_list_functions.c
  src/03.env_init.c
  src/06_builtins/46.builtin_unset.c
Labels: bug, leak

#296 278 minishell tester fix quote expansion
  _ci_cd/Makefile
  _ci_cd/minishell_main_tester.c
  _ci_cd/test_files/test01_initial_errors.c
  _ci_cd/test_files/test04_tokens_03_to_05.c
  _ci_cd/test_files/test06_tokens_cadet.c
  _ci_cd/test_files/test08_syntax_state200.c
  headers/builtins.h
  headers/expansion.h
  headers/lexer.h
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/11.state61_to_state90.c
  src/03.env_init.c
  src/04_tree_execution/23.tree_execution.c
  src/05.loop_routine.c
  src/05_expansions/30.expansion_manager.c
  src/05_expansions/31.expansion_detectors.c
  src/05_expansions/32.expansion_quotes.c
  src/05_expansions/33.expansion_tilde.c
  src/05_expansions/34.expansion_env_var.c
  src/05_expansions/36.expansion_question.c
  src/06_builtins/38.builtin_manager.c
  src/06_builtins/40.builtin_echo.c
  src/06_builtins/45.builtin_export_utils.c
  src/06_builtins/46.builtin_unset.c
  src/06_builtins/48.builtin_exit.c
  src/06_builtins/49.builtin_exit_utils.c
Labels: bug, enhancement, leak

#299 applying exit status holder
  src/01_lexer/12.error_manager_lexer.c
  src/05.loop_routine.c
Labels: enhancement

#303 302 update error message at builtin cd
  src/06_builtins/41.builtin_cd.c
  src/06_builtins/42.builtin_cd_utils.c
Labels: bug, enhancement

#305 updating FD to stderr_fileno
  src/06_builtins/48.builtin_exit.c
Labels: enhancement

#307 verifying if nxt_char at dollar sign is not empty
  src/05_expansions/31.expansion_detectors.c
Labels: bug

#310 adding exit at stdout_fileno
  src/06_builtins/48.builtin_exit.c
Labels: enhancement

#314 rolling back string compare with strlen for lexeme
  src/06_builtins/37.builtin_detectors.c
Labels: bug

#317 Feat/heredoc
  Makefile
  src/04_tree_execution/27.manage_redirects.c
  src/05.loop_routine.c
Labels: enhancement

#321 moving heredoc to a solo file
  Makefile
  headers/parser.h
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/07.token_list_functions.c
  src/02_parser/20.manage_heredoc.c
  src/05.loop_routine.c
Labels: bug

#323 fixing memory leak at ENV
  src/05_expansions/34.expansion_env_var.c
Labels: bug, leak

#324 308 fix unset for shell test
  headers/builtins.h
  src/03.env_init.c
  src/06_builtins/46.builtin_unset.c
Labels: bug

#326 Fix leaks parser
  headers/error_manager.h
  headers/lexer.h
  src/01.main.c
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/11.state61_to_state90.c
  src/02_parser/14.syntax_analysis.c
  src/02_parser/15.state100.c
  src/02_parser/16.state200_to_state300.c
  src/02_parser/19.error_manager_parser.c
  src/05.loop_routine.c
Labels: bug, leak

#329 improving echo options security
  src/06_builtins/39.builtin_utils.c
  src/06_builtins/40.builtin_echo.c
Labels: enhancement

#333 312 fix exit code at pipes
  headers/executor.h
  src/04_tree_execution/23.tree_execution.c
  src/04_tree_execution/26.manage_pipe.c
  src/06_builtins/48.builtin_exit.c
  src/07_command_execution/50.command_runner.c
Labels: bug, leak

#334 fix leaks (1 - 52 -> except 28) at Lucas tester
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/11.state61_to_state90.c
  src/03.env_init.c
  src/05_expansions/34.expansion_env_var.c
  src/05_expansions/36.expansion_question.c
  src/06_builtins/44.builtin_export.c
Labels: bug, leak

#336 applying exit_status_holder at redirects
  headers/executor.h
  src/04_tree_execution/23.tree_execution.c
  src/04_tree_execution/27.manage_redirects.c
Labels: bug

#338 337 fix redirects at minishell tests 55 of 75 - 1st attempt
  Makefile
  src/04_tree_execution/27.manage_redirects.c
Labels: bug

#346 344 fix syntax exit status code and error msgs 16 of 17
  headers/error_manager.h
  src/02_parser/15.state100.c
  src/02_parser/16.state200_to_state300.c
  src/02_parser/19.error_manager_parser.c
  src/04_tree_execution/29.manage_single_cmd.c
Labels: bug

#348 fix quoting removal
  _ci_cd/test_files/test08_syntax_state200.c
  headers/expansion.h
  headers/lexer.h
  src/01_lexer/06.check_initial_errors.c
  src/01_lexer/07.token_list_functions.c
  src/01_lexer/08.get_state.c
  src/01_lexer/11.state61_to_state90.c
  src/05_expansions/30.expansion_manager.c
  src/05_expansions/31.expansion_detectors.c
  src/05_expansions/32.expansion_quotes.c
Labels: bug, enhancement

#350 adding hashtag blocker
  .github/workflows/minishell_tester_mandatory.yml
  src/05.loop_routine.c
Labels: enhancement

#352 351 fix mandatory tests 32 of 39
  headers/executor.h
  src/04_tree_execution/29.manage_single_cmd.c
  src/06_builtins/41.builtin_cd.c
Labels: bug

#358 removing valgrind from actions
  .github/workflows/norminette.yml
  .github/workflows/our_own_tester.yml
Labels: enhancement

#362 adding new action for HEREDOC
  .github/workflows/minishell_tester_heredoc.yml
Labels: enhancement

#365 updating readline suppressions
  readline.sup
Labels: enhancement
